# Generated by Django 3.2.6 on 2021-08-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TyrName', models.CharField(max_length=128)),
                ('TyrType', models.CharField(max_length=1024)),
                ('TyrPrice', models.CharField(max_length=60)),
            ],
        ),
    ]
