# Generated by Django 3.2.6 on 2021-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyrists_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrs',
            name='TyrPhoto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
