# Generated by Django 3.2.6 on 2021-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyrists_app', '0002_tyrs_tyrphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyrs',
            name='TyrPhoto',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
