# Generated by Django 3.2.6 on 2021-08-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tyrists_app', '0003_alter_tyrs_tyrphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyrs',
            options={'ordering': ('-CreationDate',)},
        ),
        migrations.AddField(
            model_name='tyrs',
            name='Author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tyrs',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
