# Generated by Django 3.2.6 on 2021-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyrists_app', '0004_auto_20210821_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrs',
            name='image',
            field=models.ImageField(blank=True, default='tyr_default.jpg', null=True, upload_to='tyrs_imgs'),
        ),
    ]
