# Generated by Django 3.2.6 on 2021-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyrists_app', '0005_tyrs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrs',
            name='TyrPoint',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
